config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users
  resources :users, except: [:edit, :update, :destroy] do
    resources :messages, only: [:index, :show, :destroy, :new, :create]
    get :chat, to: 'messages#chat'
  end
  resources :settings, only: [:edit, :update]
  resources :posts do
    member do
      get :new_comment
      post :create_comment
      post :create_vote
    end
  end
  resources :comments, only: [:edit, :update, :destroy]
  match "lang/:locale", to: "home#change_locale", as: :change_locale, via: [:get]
  get "/explore", to: "home#explore"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  scope :unread, -> { where read: false }

  validates :content, presence: true, length: { maximum: 500 }
  validates :sender_id, presence: true
  validates :receiver_id, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show ,:destroy]
  before_action :can_manipulate?, only: [:show ,:destroy]

  def index
    @sent_messages = Message.where(sender_id: current_user.id)
    @received_messages = Message.where(receiver_id: current_user.id)
  end

  def new
    @user = User.find(params[:user_id])
    @message = Message.new(sender_id: current_user.id, receiver_id: params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])
    @message = Message.new(message_params.merge(sender_id: current_user.id, receiver_id: params[:user_id]))

    respond_to do |format|
      if @message.save
        format.html { redirect_to user_chat_path(@user), notice: t('message.created') }
        format.json { render :chat, status: :ok, location: @user }
      else
        format.html { render :new, user_id: @user.id, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def chat
    @message = Message.new
    @messages = Message.where(sender_id: [current_user.id, params[:user_id]], receiver_id: [current_user.id, params[:user_id]])
                       .order(created_at: :asc)

    @user = User.find(params[:user_id])
  end

  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to user_messages_path, notice: t('message.deleted') }
      format.json { head :no_content }
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :subject)
  end

  def set_message
    @message = Message.find(params[:id])
    @receiver = User.find(@message.receiver_id)
    @sender = User.find(@message.sender_id)
  end

  def can_manipulate?
    return if @message.receiver_id == current_user&.id || @message.sender_id == current_user&.id

    redirect_back(
      fallback_location: user_messages_path,
      flash: { alert: t('not_authorized') }
    )
  end
end

app/views/messages/_form.html.erb
<%= render 'devise/shared/error_messages', resource: @message %>

<div class="form-signin my-2 mx-auto w-75">
  <%= form_for(@message, url: user_messages_path(@user)) do |form| %>
    <div>
      <%= form.label :subject %>
      <%= form.text_field :subject, class: "form-control"%>
    </div>

    <div>
      <%= form.label :content %>
      <%= form.text_area :content, class: "form-control"%>
    </div>

    <hr>

    <div class="actions">
      <%= form.submit t('submit'), class: "btn btn-primary m-1" %>
      <%= link_to t('back'), :back, class: 'btn btn-outline-light m-1' %>
    </div>
    <% end %>
</div>

app/views/messages/chat.html.erb
<div class="container content">
  <div class="row d-flex justify-content-evenly">
    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
      <div class="card">
        <div class="card-header">Chat</div>
        <div class="card-body height3">
          <ul class="chat-list">

            <% @messages.each do |message| %>
              <% if current_user == message.sender %>
                <li class="out">
                  <div class="chat-img">
                    <img alt="Avtar" src="https://bootdey.com/img/Content/avatar/avatar6.png">
                  </div>
                  <div class="chat-body">
                    <div class="chat-message">
                      <h5><%= link_to "#{message.sender.full_name}", user_path(message.sender), class: "text-decoration-none text-light" %></h5>
                      <p><%= message.content %></p>
                    </div>
                  </div>
                </li>
              <% end %>

              <% if current_user == message.receiver %>
                <li class="in">
                  <div class="chat-img">
                    <img alt="Avtar" src="https://bootdey.com/img/Content/avatar/avatar1.png">
                  </div>
                  <div class="chat-body">
                    <div class="chat-message">
                      <h5><%= link_to "#{message.sender.full_name}", user_path(message.sender), class: "text-decoration-none text-light" %></h5>
                      <p><%= message.content %></p>
                    </div>
                  </div>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>
        <%= form_for(@message, url: user_messages_path(@user)) do |form| %>
          <div class="m-2">
            <%= form.text_area :content, class: "form-control", placeholder: t('message.respond') %>
          </div>
          <div class="actions">
            <%= form.submit t('submit'), class: "btn btn-sm btn-outline-dark my-2" %>
          </div>
        <% end %>
      </div>
      <div class="p-5 mb-4 text-light rounded-3 text-center">
        <%= link_to t(:back), @user, class: "btn btn-outline-light p-2" %>
      </div>
    </div>
  </div>
</div>

app/views/messages/index.html.erb
<h1 class="text-center my-4"><%= t('header.message') %></h1>

<ul class="nav mb-3 d-flex justify-content-center text-center" id="pills-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button id="methodAbtn" class="active btn btn-sm btn-outline-light mx-2" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#methodA" type="button" role="tab" aria-controls="pills-home" aria-selected="true"><%= t('activerecord.models.message.receive.other') %></button>
  </li>
  <li class="nav-item" role="presentation">
    <button id="methodBbtn" class="btn btn-sm btn-outline-light mx-2" data-bs-toggle="pill" data-bs-target="#methodB" type="button" role="tab" aria-controls="pills-contact" aria-selected="false"><%= t('activerecord.models.message.send.other') %></button>
  </li>
</ul>

<div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade show active" id="methodA" role="tabpanel" aria-labelledby="pills-home-tab">
    <% if @received_messages.any? %>
      <table class="table table-striped table-bordered table-hover">
        <thead class="table-primary">
        <tr>
          <th scope="col"><%= t("activerecord.attributes.message.subject") %></th>
          <th scope="col"><%= t("activerecord.attributes.message.content") %></th>
          <th scope="col"><%= t("activerecord.attributes.message.sender") %></th>
          <th scope="col"><%= t("message.actions") %></th>
        </tr>
        </thead>
        <tbody class="table-primary">
        <% @received_messages.each do |message| %>
          <tr>
            <td><%= message.subject %></td>
            <td><%= message.content %></td>
            <td><%= link_to "#{message.sender.full_name}", user_path(message.sender), class: "text-decoration-none" %></td>
            <td>
              <div class="btn-group" role="group">
                <%= link_to t("message.show_message"), user_message_path(current_user, message), class: 'btn btn-primary btn-sm' %>
                <%= link_to t("message.delete"), user_message_path(current_user, message), class: 'btn btn-danger btn-sm', data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% end %>
  </div>

  <div class="tab-pane fade" id="methodB" role="tabpanel" aria-labelledby="pills-home-tab">
    <% if @sent_messages.any? %>
      <table class="table table-striped table-bordered table-hover">
        <thead class="table-primary">
        <tr>
          <th scope="col"><%= t("activerecord.attributes.message.subject") %></th>
          <th scope="col"><%= t("activerecord.attributes.message.content") %></th>
          <th scope="col"><%= t("activerecord.attributes.message.receiver") %></th>
          <th scope="col"><%= t("message.actions") %></th>
        </tr>
        </thead>
        <tbody class="table-primary">
        <% @sent_messages.each do |message| %>
          <tr>
            <td><%= message.subject %></td>
            <td><%= message.content %></td>
            <td><%= link_to "#{message.receiver.full_name}", user_path(message.receiver), class: "text-decoration-none" %></td>
            <td>
              <div class="btn-group" role="group">
                <%= link_to t("message.show_message"), user_message_path(current_user, message), class: 'btn btn-primary btn-sm' %>
                <%= link_to t("message.delete"), user_message_path(current_user, message), class: 'btn btn-danger btn-sm', data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/messages/new.html.erb
<h1 class="text-center my-4"><%= t('message.new') %></h1>

<%= render "form", action: :new %>

app/views/messages/show.html.erb
<div class="container mt-4">
  <h1 class="mb-4"><%= t("message.show") %></h1>

  <div class="border rounded-4 bg-light text-dark">

    <% if @message %>
      <div class="mb-3">
        <p><strong><%= t("message.subject") %></strong> <%= @message.subject if @message.subject %></p>
        <p><strong><%= t("message.content") %></strong> <%= @message.content if @message.content %></p>
      </div>

      <div class="row">
        <div class="col">
          <% if @sender %>
            <p><strong><%= t("message.sender") %></strong> <%= link_to "#{@sender.full_name}", @sender, class: "text-decoration-none" %></p>
          <% end %>
        </div>
        <div class="col">
          <% if @receiver %>
            <p><strong><%= t("message.receiver") %></strong> <%= link_to "#{@receiver.full_name}", @receiver, class: "text-decoration-none" %></p>
          <% end %>
        </div>
      </div>

  </div>

  <%= link_to t('back'), :back, class: 'btn btn-outline-light mt-3' %>
  <% else %>
    <p><%= t("message.not_found") %></p>
  <% end %>

</div>