config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users
  resources :users, except: [:edit, :update, :destroy] do
    resources :messages, only: [:index, :show, :destroy, :new, :create]
    get :chat, to: 'messages#chat'
  end
  resources :settings, only: [:edit, :update]
  resources :posts do
    member do
      get :new_comment
      post :create_comment
      post :create_vote
    end
  end
  resources :comments, only: [:edit, :update, :destroy]
  match "lang/:locale", to: "home#change_locale", as: :change_locale, via: [:get]
  get "/explore", to: "home#explore"
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true

  has_one :setting, class_name: 'Setting', foreign_key: 'user_id', dependent: :destroy
  has_many :posts, class_name: 'Post', foreign_key: 'user_id', dependent: :destroy
  has_many :comments, class_name: 'Comment', foreign_key: 'user_id', dependent: :destroy
  has_many :votes, class_name: 'Vote', foreign_key: 'user_id', dependent: :destroy
  has_many :messages, class_name: "Message", foreign_key: "receiver_id"
  has_many :sent_messages, class_name: "Message", foreign_key: "sender_id"

  after_save :create_setting

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  private

  def create_setting
    return if setting.present?

    Setting.create!(user_id: id)
  end

  def self.search(search, current_user = nil)
    if search
      User.where.not(id: current_user&.id).where("lower(first_name || last_name || email) LIKE ?", "%#{search.downcase}%")
    else
      User.where.not(id: current_user&.id)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :authenticate_user!

  def index
    @users = User.search(params[:search_users], current_user)

    if params[:order_users].present?
      case params[:order_users]
      when "first_name_asc"
        @users = @users.order("first_name ASC")
      when "first_name_desc"
        @users = @users.order("first_name DESC")

      when "last_name_asc"
        @users = @users.order("last_name ASC")
      when "last_name_desc"
        @users = @users.order("last_name DESC")

      when "email_asc"
        @users = @users.order("email ASC")
      when "email_desc"
        @users = @users.order("email DESC")

      else
        flash[:alert] = t('order.invalid_value')
      end
    end

    if @users.class == Array
      @users = Kaminari.paginate_array(@users).page(params[:users_page])
    else
      @users = @users.page(params[:users_page])
    end
  end

  def show
    @user_posts = Post.where(user_id: @user.id)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_user.html.erb
<h1 class="text-center my-4"><%= t('profile.index') %></h1>

<div class="text-light rounded-3 text-start">
  <div class="container-fluid">

    <%= render "users/user_card", user: user  %>

    <div class="card-text">
      <p class="d-flex justify-content-center">

        <% if user == current_user %>
          <button class="btn btn-outline-warning m-1" type="button">
            <%= link_to t('header.edit_profile'), edit_user_registration_path, class: "text-decoration-none text-reset" %>
          </button>
        <% end %>

        <% if user != current_user %>
          <button class="btn btn btn-light m-1" type="button">
            <%= link_to t('activerecord.models.message.new'), new_user_message_path(user.id), class: "text-decoration-none text-reset" %>
          </button>
        <% end %>

        <% if user != current_user %>
          <button class="btn btn-primary m-1" type="button">
            <%= link_to t('activerecord.models.message.chat'),  user_chat_path(user.id), class: "text-decoration-none text-reset" %>
          </button>
        <% end %>

        <button class="btn btn-outline-light m-1" type="button">
          <%= link_to t(:back), :back, class: "text-decoration-none text-reset" %>
        </button>

      </p>

      <%= render "users/user_posts"  %>
    </div>
  </div>
</div>

app/views/users/_user_card.html.erb
<div class="card bg-dark p-4 my-2">
  <div class="d-flex my-auto">
    <div class="text-start">
      <%= link_to "#{user.full_name}", user, class: "text-light text-decoration-none h1 fw-bold" %>
      <p class="card-text">
        <strong><%= user.email %></strong>
      </p>
    </div>
  </div>
</div>

app/views/users/_user_posts.html.erb
<% @user_posts.each do |post| %>
  <%= render 'shared/post', post: post %>
<% end %>

app/views/users/index.html.erb
<h1 class="text-center my-4"><%= t('activerecord.models.user.other') %></h1>

<div id="users" class="text-center mx-auto w-100">

    <%= render "shared/users_search_form", action: 'users' %>

    <% @users.each do |user| %>
      <%= render "users/user_card", user: user %>
    <% end %>
    <%= page_entries_info @users %>
    <%= paginate @users, theme: 'bootstrap-5', pagination_class: "my-3 pagination-sm flex-wrap justify-content-center" %>
</div>

app/views/users/show.html.erb
<%= render @user %>