config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users
  resources :users, except: [:edit, :update, :destroy] do
    resources :messages, only: [:index, :show, :destroy, :new, :create]
    get :chat, to: 'messages#chat'
  end
  resources :settings, only: [:edit, :update]
  resources :posts do
    member do
      get :new_comment
      post :create_comment
      post :create_vote
    end
  end
  resources :comments, only: [:edit, :update, :destroy]
  match "lang/:locale", to: "home#change_locale", as: :change_locale, via: [:get]
  get "/explore", to: "home#explore"
end

app/views/shared/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong><%= alert %></strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/shared/_comment.html.erb
<div class="card mb-2">
  <div class="card-body">
    <p class="d-flex justify-content-start text-dark fw-bold"><%= comment.content %></p>

    <div class="d-flex justify-content-between">
      <div class="d-flex flex-row align-items-center">
        <p class="small text-muted mb-0"><%= comment.created_at.strftime("%d. %m. %Y - %H:%M") %></p>
      </div>

      <div class="d-flex flex-row align-items-center">
        <% if comment.user_id == current_user&.id %>
          <%= link_to t(:edit), edit_comment_path(comment), class: "text-muted text-decoration-none my-auto" %>
          <%= button_to t(:delete), comment_path(comment), data: { confirm: I18n.t(:delete_confirmatiom) }, method: :delete, class: "text-danger btn btn-link text-decoration-none" %>
        <% end %>
      </div>

      <div class="d-flex flex-row align-items-center">
        <p class="small mb-0 ms-2"><%= link_to comment.user.full_name, comment.user, class: "text-muted tex-decoration-none" %> %>></p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="d-flex justify-content-center align-items-center mb-3">
  <div>
    <% if user_signed_in? %>
      <b><%= current_user.full_name %></b>, <%= t('footer.welcome') %>
    <% end %>
    <%= t('footer.follow') %> <a href="https://github.com/xPalo/asos_cms" class="text-white" target="_blank" >GitHub</a>
  </div>

  <div class="m-2">|</div>

  <div class="dropdown language" id="dropdown">
    <button class="btn btn-sm btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="flag-icon flag-icon-<%= t("flag_icon.#{I18n.locale}") %>"></span> <%= t("#{I18n.locale}") %>
    </button>
    <div class="dropdown-menu dropdown-menu-right text-right language mx-0 px-0">

      <%= link_to change_locale_path("sk"), class: "dropdown-item" do %>
        <span class="flag-icon flag-icon-sk"></span> <%= t("sk") %>
      <% end %>

      <%= link_to change_locale_path("en"), class: "dropdown-item" do %>
        <span class="flag-icon flag-icon-us"></span> <%= t("en") %>
      <% end %>

    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div>
  <%= link_to I18n.t("title"), root_path, class: "navbar-brand fs-2 my-auto fw-bold float-md-start text-white" %>
  <nav class="nav nav-masthead justify-content-center float-md-end m-0">
  <%= link_to t('header.explore'), explore_path, class: "nav-link fw-bold px-2 #{current_class?(explore_path, "light")}" %>
  <% if user_signed_in? %>
      <%= link_to t('header.feed'), posts_path, class: "nav-link fw-bold px-2 #{current_class?(posts_path, "light")}" %>
      <%= link_to t('activerecord.models.user.other'), users_path, class: "nav-link fw-bold px-2 #{current_class?(users_path, "light")}" %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle fw-bold" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= I18n.t('header.my_profile') %>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to I18n.t('header.overview'), user_path(id: current_user.id), class: "nav-link text-dark fw-bold px-2" %></li>
          <li><%= link_to I18n.t('header.edit_profile'), edit_user_registration_path, class: "nav-link text-dark fw-bold px-2" %></li>
          <li><%= link_to I18n.t('header.settings'), edit_setting_path(id: current_user.setting.id), class: "nav-link text-dark fw-bold px-2" %></li>
          <li><%= link_to I18n.t('activerecord.models.message.other'), user_messages_path(current_user), class: "nav-link text-dark fw-bold px-2" %></li>
        </ul>
      </li>
      <%= button_to I18n.t('header.log_out'), destroy_user_session_path, method: :delete, class: "btn btn-link nav-link fw-bold px-2 text-danger danger" %>
    <% else %>
      <%= link_to I18n.t('header.sign_up'), new_user_registration_path, class: "nav-link fw-bold px-2 #{current_class?(new_user_registration_path, "light")}" %>
      <%= link_to I18n.t('header.log_in'), new_user_session_path, class: "nav-link fw-bold px-2 text-info #{current_class?(new_user_session_path, "info")}" %>
    <% end %>
  </nav>
</div>

app/views/shared/_notice.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong><%= notice %></strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/shared/_post.html.erb
<div class="card text-dark text-center my-2">
  <% if post.user == current_user %>
    <div class="card-header p-0">
      <div class="d-flex justify-content-end bg-light">
        <%= link_to t(:edit), edit_post_path(post), class: "text-muted text-decoration-none my-auto" %>
        <%= button_to t(:delete), post_path(post), data: { confirm: I18n.t(:delete_confirmatiom) }, method: :delete, class: "text-danger btn btn-link text-decoration-none" %>
      </div>
    </div>
    <% end %>
  <div class="card-body pt-2 pb-1 px-3">
    <h5 class="card-title"><%= link_to post.title, post, class: "text-dark text-decoration-none h1 fw-bold" %></h5>
    <p class="card-text mb-0"><%= post.content %></p>
        <div class="d-flex justify-content-end">
          <%= link_to(post.user.full_name, post.user, class: "text-muted text-decoration-none") unless current_user&.id == post.user_id %>
        </div>
  </div>
  <div class="card-footer text-muted text-light">
    <div class="d-flex justify-content-between">
      <%= post.created_at.strftime("%d. %m. %Y - %H:%M") %>

      <div class="d-flex my-auto">
        <%= button_to('▲', create_vote_post_path(post, vote: { vote_type: 'upvote' }), method: :post, class: "btn btn-link text-decoration-none text-muted") unless current_user&.id == post.user_id %>
        <p class="my-auto">
          <%= post.votes_count %>
        </p>
        <%= button_to('▼', create_vote_post_path(post, vote: { vote_type: 'downvote' }), method: :post, class: "btn btn-link text-decoration-none text-muted") unless current_user&.id == post.user_id %>
      </div>

      <%= link_to t('activerecord.attributes.comment.add') + " (#{post.comments_count})", new_comment_post_path(post), class: "text-decoration-none text-muted" %>
    </div>
  </div>
</div>

app/views/shared/_posts_search_form.html.erb
<form action="<%= action %>" method="get" class="form mb-3 justify-content-center text-center my-auto">
  <div class="form-group d-flex justify-content-center my-auto mb-2">
    <input type="text" id="search_posts" name="search_posts" placeholder="<%= t('order.search') %>" class="form-control w-50 mx-2" value="<%= params[:search_posts] %>">
  </div>
  <div class="form-group d-flex justify-content-center my-auto mb-2">
    <select class="form-select w-50 d-flex justify-content-center" aria-label="default select form-select example" name="order_posts">
      <option value="" disabled <%= 'selected' if params[:order_posts].blank? %> ><%= t('order.order_by') %></option>
      <% %w(title_asc title_desc content_asc content_desc votes_asc votes_desc comments_count_asc comments_count_desc).each do |attr| %>
        <option value="<%= attr %>" <%= 'selected' if params[:order_posts] == attr %>><%= t("order.#{attr}") %></option>
      <% end %>
    </select>
  </div>
  <button type="submit" class="btn btn-outline-light mx-2"><%= t('order.submit') %></button>
</form>

app/views/shared/_prezentation.html.erb
<script type="text/javascript" charset="utf-8">

    document.getElementById("methodAbtn").addEventListener("click", function(event){
        localStorage.setItem("explore_category", "methodAbtn");
    });
    document.getElementById("methodBbtn").addEventListener("click", function(event){
        localStorage.setItem("explore_category", "methodBbtn");
    });

    $(document).ready(function()
    {
        if (localStorage.getItem("explore_category"))
        {
            document.getElementById("methodAbtn").setAttribute("class", "btn btn-sm btn-outline-light mx-2");
            document.getElementById("methodBbtn").setAttribute("class", "btn btn-sm btn-outline-light mx-2");
            document.getElementById(localStorage.getItem("explore_category")).setAttribute("class", "active btn btn-sm btn-outline-light mx-2");
        }
        else
        {
            localStorage.setItem("explore_category", "methodAbtn")
        }
    });

    $(`#${localStorage.getItem("explore_category")}`).click();

</script>

app/views/shared/_users_search_form.html.erb
<form action="<%= action %>" method="get" class="form mb-3 justify-content-center text-center my-auto">
  <div class="form-group d-flex justify-content-center my-auto mb-2">
    <input type="text" id="search_users" name="search_users" placeholder="<%= t('order.search') %>" class="form-control w-50 mx-2" value="<%= params[:search_users] %>">
  </div>
  <div class="form-group d-flex justify-content-center my-auto mb-2">
    <select class="form-select w-50 d-flex justify-content-center" aria-label="default select form-select example" name="order_users">
      <option value="" disabled <%= 'selected' if params[:order_users].blank? %> ><%= t('order.order_by') %></option>
      <% %w(first_name_asc first_name_desc last_name_asc last_name_desc email_asc email_desc).each do |attr| %>
        <option value="<%= attr %>" <%= 'selected' if params[:order_users] == attr %>><%= t("order.#{attr}") %></option>
      <% end %>
    </select>
  </div>
  <button type="submit" class="btn btn-outline-light mx-2"><%= t('order.submit') %></button>
</form>