config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users
  resources :users, except: [:edit, :update, :destroy] do
    resources :messages, only: [:index, :show, :destroy, :new, :create]
    get :chat, to: 'messages#chat'
  end
  resources :settings, only: [:edit, :update]
  resources :posts do
    member do
      get :new_comment
      post :create_comment
      post :create_vote
    end
  end
  resources :comments, only: [:edit, :update, :destroy]
  match "lang/:locale", to: "home#change_locale", as: :change_locale, via: [:get]
  get "/explore", to: "home#explore"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'post_id', dependent: :destroy
  has_many :votes, class_name: 'Vote', foreign_key: 'post_id', dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true

  scope :is_public, -> { where(is_public: true) }

  def comments_count
    comments.count
  end

  def upvotes
    self.votes.where(vote_type: 'upvote').count
  end

  def downvotes
    self.votes.where(vote_type: 'downvote').count
  end

  def votes_count
    upvotes - downvotes
  end

  private

  def self.search(search)
    if search
      Post.is_public
          .joins(:user)
          .where("lower(posts.title || posts.content || users.first_name || users.last_name || users.email) LIKE ?", "%#{search.downcase}%")
    else
      Post.is_public
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :new_comment, :create_comment, :create_vote]
  before_action :authenticate_user!
  before_action :can_manipulate?, only: [:edit, :update, :destroy]

  def index
    @posts = Post.is_public.includes(:user, :comments).search(params[:search_posts])

    if params[:order_posts].present?
      case params[:order_posts]
      when "title_asc"
        @posts = @posts.order("title ASC")
      when "title_desc"
        @posts = @posts.order("title DESC")

      when "content_asc"
        @posts = @posts.order("content ASC")
      when "content_desc"
        @posts = @posts.order("content DESC")

      when "votes_asc"
        @posts = @posts.sort_by { |b| b.votes_count }
      when "votes_desc"
        @posts = @posts.sort_by { |b| -b.votes_count }

      when "comments_count_asc"
        @posts = @posts.sort_by { |b| b.comments_count }
      when "comments_count_desc"
        @posts = @posts.sort_by { |b| -b.comments_count }

      else
        flash[:alert] = t('order.invalid_value')
      end
    end

    if @posts.class == Array
      @posts = Kaminari.paginate_array(@posts).page(params[:page])
    else
      @posts = @posts.page(params[:page])
    end
  end

  def show
    @comments = @post.comments.order(:created_at)
  end

  def new
    @post = Post.new(is_public: true)
  end

  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_path(@post), notice: t('post.created') }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_path(@post), notice: t('post.updated') }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_path, notice: t('post.deleted') }
      format.json { head :no_content }
    end
  end

  def new_comment
    @comment = Comment.new
  end

  def create_comment
    @comment = Comment.new(comment_params.merge(user_id: current_user.id, post_id: @post.id))

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@post), notice: t('activerecord.attributes.comment.added') }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new_comment, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_vote
    return if current_user&.id == @post&.user_id

    @vote = Vote.find_or_initialize_by(user_id: current_user.id, post_id: @post.id)

    @vote.assign_attributes(vote_params)

    respond_to do |format|
      if @vote.save && current_user&.id != @post&.user_id
        format.html { redirect_to post_path(@post), notice: t('activerecord.attributes.vote.added') }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :show, status: :unprocessable_entity }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_post
    @post = Post.includes(:user, :comments).find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :is_public)
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def vote_params
    params.require(:vote).permit(:vote_type)
  end

  def can_manipulate?
    return if @post.user_id == current_user&.id

    redirect_back(
      fallback_location: posts_path,
      flash: { alert: t('not_authorized') }
    )
  end
end

app/views/posts/_comment_form.html.erb
<%= render 'devise/shared/error_messages', resource: @comment %>

<div class="form-signin my-4 mx-auto w-75">
  <%= form_for(@comment, url: create_comment_post_path(@post)) do |form| %>
    <div>
      <%= form.label :content %>
      <%= form.text_area :content, class: "form-control" %>
    </div>

    <hr>

    <div class="actions">
      <%= form.submit t("button_#{action}"), class: "btn btn-primary my-auto" %>
    </div>
  <% end %>
</div>

app/views/posts/_form.html.erb
<h1 class="text-center"> <%= t("post.#{action}") %> </h1>

<%= render 'devise/shared/error_messages', resource: @post %>

<div class="form-signin my-4 mx-auto w-75">
  <%= form_for(@post) do |form| %>

    <div>
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control"%>
    </div>

    <div>
      <%= form.label :content %>
      <%= form.text_area(:content, class: "form-control") %>
    </div>

    <div>
      <%= form.label :is_public %>
      <%= form.check_box :is_public, class: "form-check-input" %>
    </div>

    <hr>

    <div class="actions">
      <%= form.submit t("button_#{action}"), class: "btn btn-primary m-1" %>
      <%= link_to t('back'), :back, class: 'btn btn-outline-light m-1' %>
    </div>
  <% end %>
</div>

app/views/posts/_user_comments.html.erb
<% if comments&.any? %>
  <% comments.each do |comment| %>
    <%= render 'shared/comment', comment: comment %>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<%= render "form", post: @post, action: :edit %>

app/views/posts/index.html.erb
<h1 class="text-center my-4"><%= t('activerecord.models.post.other') %></h1>

<div id="posts" class="text-center mx-auto w-100">

  <%= render "shared/posts_search_form", action: 'posts' %>

  <div class="d-flex justify-content-center m-5">
    <%= link_to t('post.new'), new_post_path, class: "btn btn-light text-success" %>
  </div>

  <% if @posts.length > 0 %>
    <% @posts.each do |post| %>
      <%= render 'shared/post', post: post %>
    <% end %>
  <% end %>

  <%= page_entries_info @posts %>
  <%= paginate @posts, theme: 'bootstrap-5', pagination_class: "my-3 pagination-sm flex-wrap justify-content-center" %>

</div>

app/views/posts/new_comment.html.erb
<%= render 'shared/post', post: @post %>
<%= render "comment_form", action: :new %>

app/views/posts/show.html.erb
<%= render 'shared/post', post: @post %>
<%= render 'user_comments', comments: @comments %>

<%= link_to t('back'), :back, class:'btn btn-outline-light' %>